
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
# Lighting Devices
light: !include light.yaml
# Sensors
sensor: !include config/sensors.yaml

#adaptive_lighting: !include config/adaptive_lighting.yaml

# LG WebOS TV
webostv:
    host: !secret webostv_ip
    name: LG OLED
    
media_player: !include media_player.yaml

# YAML Lovelace config
lovelace: !include lovelace.yaml

input_boolean:
  morning_trigger:
    name: Morning first trigger
    initial: off

binary_sensor:
  # Bayesian Going to Bed
  - platform: bayesian
    name: 'Going_to_Bed'
    prior: 0.1
    probability_threshold: 0.9
    observations:
      - platform: 'state'
        entity_id: 'media_player.onkyoreceiver'
        prob_given_true: 0.5
        prob_given_false: 0.1
        to_state: 'off'
      - platform: 'state'
        entity_id: 'sun.sun'
        prob_given_true: 0.8
        prob_given_false: 0.1
        to_state: 'below_horizon'
      - platform: 'state'
        entity_id: 'binary_sensor.upstairs_motion'
        prob_given_true: 0.2
        prob_given_false: 0.1
        to_state: 'on'
