name: Workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        version: 3.7
    - name: Install dependencies
      run: |
        pip install git+git://github.com/home-assistant/home-assistant.git@dev
        pip install -r requirements.txt
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        python3 -m pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}