- id: '1543989378173'
  alias: Devi Wakeup
  trigger:
  - entity_id: binary_sensor.multi_sensor_first_floor_motion_sensor_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '6:00'
      before: '8:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_boolean.morning_trigger
      state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.morning_trigger
  - service: scene.turn_on
    entity_id: scene.living_high
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_speaker
      media_content_id: http://stream1.cprnetwork.org:80/cpr1_aac
      media_content_type: music
  - delay: 00:30:00
  - service: media_player.media_stop
    data:
      entity_id: media_player.living_room_speaker
  - service: scene.turn_on
    entity_id: scene.living_mid
- id: '1543989378174'
  alias: Change input boolean
  trigger:
    platform: time
    at: 08:00:00
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.morning_trigger
