    # Onkyo Volume
    - platform: template
      sensors:
        onkyo_volume:
          value_template: >
            {% if is_state('media_player.onkyoreceiver', 'on')  %}
              {{ (states.media_player.onkyoreceiver.attributes.volume_level | float * 80 | int) }}
            {% else %}
              0
            {% endif %}
          friendly_name: 'Onkyo Volume'

    # Container performance sensor
    - platform: systemmonitor
      resources:
        - type: disk_use_percent
          arg: /
        - type: memory_use_percent
        - type: processor_use

    # Time and date
    - platform: time_date
      display_options:
        - 'time'
        - 'date'
